import Head from "next/head"
import Image from "next/image"
import Header from "../components/Header"
import Body from "../components/Body"
import Footer from "../components/Footer"
import EstadisticaCandidatos from "../components/EstadisticaCandidatos"

const Estadisticas = () => {
    return (
        <div className="flex flex-col h-screen justify-between">
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <Body>
                <EstadisticaCandidatos />
            </Body>
            <Footer />
        </div>
    )
}

export default Estadisticas
