import Head from 'next/head'
import Image from 'next/image'

// Components
import Navbar from '../src/components/Navbar'

import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Votaciones - Platzi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Navbar />
        <h1 className="text-5xl font-bold underline">
          !Votaciones Platzi¡
        </h1>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/stban94diaz"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Esteban Diaz
        </a>
      </footer>
    </div>
  )
}
