import Head from 'next/head'
import { useWeb3React } from '@web3-react/core'

// Components
import Navbar from '../src/components/Navbar'
import Vote from '../src/components/Vote'
import Votes from '../src/components/Votes'

import styles from '../styles/Home.module.scss'

export default function Home() {
  const { active } = useWeb3React()
  return (
    <div className={styles.container}>
      <Head>
        <title>Votaciones - Platzi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Navbar />
        <h1 className="text-5xl font-bold underline">
          !Votaciones Platzi¡
        </h1>
        {active
          ? (<>
            <Vote />
            <Votes />
          </>)
          : <b className="mt-3 text-2xl">
            Aun no estas conectado, por favor conecta tu walet.
          </b>}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/stban94diaz"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Esteban Diaz para Anii 💚
        </a>
      </footer>
    </div>
  )
}
