import Head from "next/head"
import Image from "next/image"
import Header from "../components/Header.tsx"
import Body from "../components/Body"
import Footer from "../components/Footer"
import Tarjeton from "../components/Tarjeton"

export default function Home() {
    return (
        <div className="flex flex-col h-screen justify-between">
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <Body>
                <Tarjeton />
            </Body>
            <Footer />
        </div>
    )
}
